### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by thegreenbutcher** [VampMC/vampmc-issue-tracker#1]
Reporter:  the butcher / The_Greenbutcher

Summary: 
While playing on VampMC i purchased in game items from there online store. 
such as 
Harmony Rank 
where it states that you can set unlimited homes and /sell all both of these are false as you do not have permission to do these commands 
Spawner God Kit 
In this kit it states that is gives a sell wand which when using it is clear that you don't receive this item 
Mobgrinder God kit 
in this kit you are meant to get a money pouch of mob coin which is clear you don't revive 
Battle Pass
the battle pass asked you to complete challenges to gain rewards on the server. some of the challenges are broken and don't count your progress at all.
Panda pet
Perry Pet
 after purchasing these pets you would expect to be able to do /pets and click on them and receive them this is not the case and says that you have not purchased any of them 

Steps to Reproduce: 
when you type /sethome and any name it says that you can't set more then three homes and with the /sellalll it says you don't have permission 

God kits: when heading to spawn and going to the god kit npc you can click on your paid kit and the items will come into your inventory but some items like the sell wand and the mobcoin will not be there

when trying to activate pets you are told that you have nor purchased any of them

Expected Results: 

i would expect that when something it put onto the store it is tested before you start to charge customers.

i am no requesting a full refund of these products due to them not working as listed and intended after being informed by owners that they are 100 % sure that everything on the store works  

Actual Results;
that all issues with paid items and ingame perks would be fixed and a refund will be processed 

thanks Thegreenbutcher

**Comment by hffmnnj** [comment]
You need to make a report for each issue you find, not a mega post. Our GitHub is also not used for refunds. Please make individual posts regarding issues, thanks.

**Comment by thegreenbutcher** [comment]
you legit told me to post it on here

**Comment by thegreenbutcher** [comment]
and just read it one by one
