### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by thegreenbutcher** [VampMC/vampmc-issue-tracker#2]
harmony rank 
in the game ATM there are multiple bugs with the harmony rank such as a few of the commands don't work and some of the rewards that it is meant to give also don't work. these things include only having 3 set-homes and sell all not working also for the first few days of the server i did not get my crate keys from the daily rewards. 

set-home bug
when you have already set 3 homes and you try and do /set-home for a fourth time it will say in the chat that the players limit of 3 set-home has been reached. Not allowing you to have any more then 3

crates 
when you buy the harmony rank it lists that you will be able to use /dailyrewards for 1million dollars and 3x legendary keys 
while i was on daily and using up my reward every 24 hours i would receive the 3 keys. But when i would head to the crates it would say my balance is only 1

the results i am looking for these bugs is that the harmony rank command bug with the set homes is changed to the the players limit is increased to unlimited not 3 and for the bug with the crates i am looking to work with staff and make sure that every time you use you/daily reward you are given your 3 keys and they all work giving you 3 spins of the chest.

**Comment by hffmnnj** [comment]
Closed, didn't follow the format.
